# Changes here will be overwritten by Copier
_commit: v2.3.1
_src_path: harmon-init
bunch_add: true
devcontainer: false
git_init: true
github_collaboration_templates: true
github_release_init: true
github_remote_create: true
license: mit
obsidian_project_add: false
project_description: My dotfiles (.zshrc, .gitconfig, terminal config, ghostty, starship,
    etc.) managed with Chezmoi
project_name: Harmon Dotfiles
project_slug: harmon-dotfiles
project_url: 'TODO: project_url'
run_task_bootstrap: false
run_task_install: false
